# Site settings
title: "hot ideas coming right up"
email: tudor@saitoc.me
description: "ready or  not, here i come!" 
username: tudr
baseurl: ""
url: "https://idea.tudr.co"
paginate: 10
paginate_path: "/halaman/:num/"
date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
highlighter: rouge 

# Google services
#google_analytics:
#google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: tudr

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 

# Social icons
github_username: tudr
bitbucket_username:
stackoverflow_id:
twitter_username: tudorsnyc
skype_username: tsaitoc
steam_nickname:
google_plus_id: tudor@saitoc.me
linkedin_username: tudorsnyc
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'tudor@saitoc.me'
    content:  'just wanted to say bah!'
    subject:  'hi :)'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'


# Build settings
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
